apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app:
      postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          ports:
            - name: postgres-port
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: sardor
      nodeSelector:
        zone: eu-north-1a
      volumes:
        - name: postgres-data
          awsElasticBlockStore:
            volumeID: vol-0b1825b8738593e61
            fsType: ext4
      initContainers:
        - name: cleanup
          image: busybox:latest
          command: [ 'sh', '-c', 'rm -rf /var/lib/postgresql/data/lost+found' ]
        - name: init-sql
          image: postgres:16
          command: [ 'sh', '-c', 'psql -U postgres -c "CREATE DATABASE loomo;"' ]
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data